/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thread.sample;

import org.springframework.boot.ExitCodeGenerator;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import thread.sample.command.AbstractCommand;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
      try (ConfigurableApplicationContext ctx = SpringApplication.run(App.class, args)) {
        AbstractCommand command = (AbstractCommand) ctx.getBean(args[0]);
        System.exit(SpringApplication.exit(ctx, new ExitCodeGenerator() {
          @Override
          public int getExitCode() {
            try {
              return command.execute(args);
            }
            catch (Exception e) {
              e.printStackTrace();
              return 2;
            }
          }
        }));
      } catch(Exception e) {
        e.printStackTrace();
      }
    }
}
